apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-service
  template:
    metadata:
      labels:
        app: book-service
    spec:
      containers:
        - name: book-service
          image: sarabedier/book-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: BOOK_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: BOOK_DB_URL
            - name: BOOK_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOOK_DB_USERNAME
            - name: BOOK_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: BOOK_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
