apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: sarabedier/notification-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: NOTIFICATION_DB_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NOTIFICATION_DB_URL
            - name: NOTIFICATION_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NOTIFICATION_DB_USERNAME
            - name: NOTIFICATION_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: NOTIFICATION_DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP
