spring:
  application:
    name: order-service
server:
  port: 8083
book:
  service:
    url: ${BOOK_SERVICE_URL:http://localhost:8082/books}
notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084/notifications}
